Add Deployment to Test

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,11 +1,23 @@
 #!/usr/bin/env bash
-set -e # halt script on error
-bundle exec jekyll build --config _config.yml,_site_bicton_ac_uk.yml
-bundle exec jekyll build --config _config.yml,_site_cornwall_ac_uk.yml
-bundle exec jekyll build --config _config.yml,_site_duchy_ac_uk.yml
-bundle exec jekyll build --config _config.yml,_site_falmouthmarineschool_ac_uk.yml
+if [ "$TRAVIS_BRANCH" -= "$Octopus" ]; then
+    set -e # halt script on error
+    JEKYLL_ENV=production
+    echo "PRODUCTION BUILD"
+fi
 
-bundle exec htmlproofer ./_site/bicton_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/bicton_ac_uk/error.txt 2>&1
-bundle exec htmlproofer ./_site/cornwall_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/cornwall_ac_uk/error.txt 2>&1
-bundle exec htmlproofer ./_site/duchy_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/duchy_ac_uk/error.txt 2>&1
-bundle exec htmlproofer ./_site/falmouthmarineschool_ac_uk --url-ignore "/#.*/" --check-html "true" --disable-external > ./_site/falmouthmarineschool_ac_uk/error.txt 2>&1
+if [ "$TRAVIS_BRANCH" != "$Octopus" ]; then
+    JEKYLL_ENV=development
+    echo "DEVELOPMENT BUILD"
+fi
+
+echo "BUILD - Start Bicton"
+bundle exec jekyll build --config _config.yml,_site_bicton_ac_uk.yml
+
+echo "BUILD - Start Cornwall"
+bundle exec jekyll build --config _config.yml,_site_cornwall_ac_uk.yml
+
+echo "BUILD - Start Duchy"
+bundle exec jekyll build --config _config.yml,_site_duchy_ac_uk.yml
+
+echo "BUILD - Start Falmouth"
+bundle exec jekyll build --config _config.yml,_site_falmouthmarineschool_ac_uk.yml
